name: Yandex Cloud Auto-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
      CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SA_JSON }}

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }} .
          docker push cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}

      - name: Connect to Yandex Cloud VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login --username oauth --password ${{ secrets.YANDEX_KEY }} cr.yandex
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps -aq)
            sudo docker pull cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}
            sudo docker run -d -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} -e API_KEY=${{ secrets.API_KEY }} --name english-project-bot cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}
