name: Yandex Cloud Auto-Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
      CR_REPOSITORY: ${{ secrets.CR_REPOSITORY }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Output
        run: |
          echo "Running deployment with IMAGE_TAG: $IMAGE_TAG"
          echo "Confirming secret keys are set..."
          if [ -z "${{ secrets.YANDEX_SA_JSON }}" ]; then
            echo "YANDEX_SA_JSON is not set."
          else
            echo "YANDEX_SA_JSON is set."
          fi

      - name: Login to Yandex Cloud Container Registry
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_SA_JSON }}

      - name: Build and push Docker image
        run: |
          docker build -t cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }} .
          docker push cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}

      - name: Connect to Yandex Cloud VM via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.VM_SSH_PRIVATE_KEY }}
          script: |
            sudo docker login --username oauth --password ${{ secrets.YANDEX_KEY }} cr.yandex
            sudo docker stop $(sudo docker ps -q)
            sudo docker rm $(sudo docker ps -aq)
            sudo docker pull cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}
            sudo docker run -d -e BOT_TOKEN=${{ secrets.BOT_TOKEN }} -e GPT_TOKEN=${{ secrets.GPT_TOKEN }}  -e DATABASE_URL=${{ secrets.DATABASE_URL }} -e PROXY_HOST=${{ secrets.PROXY_HOST }} -e PROXY_PORT=${{ secrets.PROXY_PORT }} -e PROXY_USERNAME=${{ secrets.PROXY_USERNAME }} -e PROXY_PASSWORD=${{ secrets.PROXY_PASSWORD }} --name persona_chat_bot cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPOSITORY }}:user${{ env.IMAGE_TAG }}
